# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "///////////////////kecoa"
license = "MIT"
licenselink = "https://github.com/matcornic/hugo-theme-learn/blob/master/LICENSE.md"
description = "Documentation theme for Hugo, based on Grav Learn theme"
homepage = "https://kecoa.netlify.app"
repo = "https://github.com/matcornic/hugo-theme-learn"
tags = ["documentation", "grav", "learn", "doc", "search"]
features = ["documentation", "menu", "nested sections", "search", "mermaid"]
min_version = 0.25

[author]
  name = "kecoa"
  homepage = "https://kecoa.netlify.app"

[original]
  name = "kecoa"
  homepage = "https://kecoa.netlify.app"
  repo = "https://github.com/getgrav/grav-learn"
